
from typing import Protocol, List, Tuple, Dict, Optional
from .order import Order, Trade, Side

class OrderBook(Protocol):
    def add_order(self, order: Order) -> None: ...
    def match(self) -> List[Trade]: ...
    def cancel_order(self, order_id: int) -> bool: ...
    def best_bid(self) -> Optional[Tuple[float, int]]: ...
    def best_ask(self) -> Optional[Tuple[float, int]]: ...
    def depth(self, k: int = 5) -> Dict[str, List[Tuple[float, int]]]: ...
    def get_orders_at_price(self, side: Side, price: float) -> List[Order]: ...
